#!/usr/bin/python3

from enum import Enum
import argparse
import urllib.parse
import urllib.request
import urllib.error
import json
#import re
#import logging

USERAGENT = 'gitHost/0.0.1.0' # 何かしら指定しないとhubで怒られる

# main :: IO Int
def main():
    rootp = argparse.ArgumentParser(description='manage git remote host')
    subp = rootp.add_subparsers(description='')
    repop = subp.add_parser('repo', help='manipulate remote repo')
    addp = subp.add_parser('add', help='add hosting service provider & user')
    args = rootp.parse_args()
    print(args)
    return undefined

# :: Str -> Str -> urllib.request.HTTPResponse
def getBucketUserOwnRepos(user, token):
    return undefined

# :: Str -> Str -> urllib.request.HTTPResponse
def getHubUserOwnRepos(user, token):
    return undefined

# :: Str -> Str -> urllib.request.HTTPResponse
def getLabUserOwnRepos(user, token):
    return undefined

# undefined :: a
undefined = None

if __name__ == "__main__" :
  exit(main())

# vim:fenc=utf-8 ff=unix ft=python ts=4 sw=4 sts=4 si et fdm=indent fdl=0 fdn=1:
# vim:cinw=if,elif,else,for,while,try,except,finally,def,class:
