#!/usr/bin/python3

import sys
import http.client
#import argparse

hubkey = "5d880030bec3f4445204"
hubsecret = "5adba848859bac5638f11cf51b2367a60e104a9f"

# main :: IO Int
def main():
    #parser = argparse.ArgumentParser()
    #args = parser.parse_args()
    prms = sys.argv[1:]
    hubOauth(hubkey, hubsecret, "repo")
    return 0

# hubOauth :: Str -> Str -> Str -> 
def hubOauth(key, secret, scope):
    method = "GET"
    hostname = "github.com"
    path = "/login/oauth/authorize"
    url = "https://github.com/login/oauth/authorize"
    #params = { "client_id": key
    #        , "scope": scope
    #        , "state": "asdfjkl"
    #        }
    conn = http.client.HTTPSConnection(hostname)
    conn.request(method, path)
    response = conn.getresponse()
    if response.status != 200 :
        print(response.read())
        exit(str(response.status) + " " + response.reason)
    print(response.read())
    undefined

# undefined :: a
undefined = None

if __name__ == "__main__" :
  exit(main())

# vim:fenc=utf-8 ff=unix ft=python ts=4 sw=4 sts=4 si et fdm=indent fdl=99 fdn=1:
# vim:cinw=if,elif,else,for,while,try,except,finally,def,class:
